### ISSUE TITLE
Leihs does not come up again after system reboot

### ISSUE THREAD

**Issue by old-hell** [leihs/leihs-instance#2]
Leihs does not come up again after system reboot:

```
Jan 31 15:22:13 leihs ruby[500]: : CREATE DATABASE "leihs" ENCODING = 'unicode'
Jan 31 15:22:13 leihs ruby[500]: Couldn't create database for {"adapter"=>"postgresql", "host"=>"localhost", "port"=>5432, "pool"=>25, "encoding"=>"unicode", "username"=>"root", "password"=>"root", "database"=>"leihs"}
Jan 31 15:22:13 leihs ruby[500]: rake aborted!
Jan 31 15:22:13 leihs ruby[500]: ActiveRecord::StatementInvalid: PG::DuplicateDatabase: FEHLER:  Datenbank »leihs« existiert bereits
Jan 31 15:22:13 leihs ruby[500]: : CREATE DATABASE "leihs" ENCODING = 'unicode'
Jan 31 15:22:13 leihs ruby[500]: /home/leihs-database/.rubies/ruby-2.4.2/bin/bundle:23:in `load'
Jan 31 15:22:13 leihs ruby[500]: /home/leihs-database/.rubies/ruby-2.4.2/bin/bundle:23:in `<main>'
Jan 31 15:22:13 leihs ruby[500]: PG::DuplicateDatabase: FEHLER:  Datenbank »leihs« existiert bereits
Jan 31 15:22:13 leihs ruby[500]: /home/leihs-database/.rubies/ruby-2.4.2/bin/bundle:23:in `load'
Jan 31 15:22:13 leihs ruby[500]: /home/leihs-database/.rubies/ruby-2.4.2/bin/bundle:23:in `<main>'
Jan 31 15:22:13 leihs ruby[500]: Tasks: TOP => db:create
Jan 31 15:22:13 leihs ruby[500]: (See full trace by running task with --trace)
Jan 31 15:22:13 leihs systemd[1]: leihs-migration.service: Main process exited, code=exited, status=1/FAILURE
Jan 31 15:22:13 leihs systemd[1]: Failed to start Leihs Migration Service.
Jan 31 15:22:13 leihs systemd[1]: Dependency failed for Leihs Legacy Service.
Jan 31 15:22:13 leihs systemd[1]: leihs-legacy.service: Job leihs-legacy.service/start failed with result 'dependency'.
Jan 31 15:22:13 leihs systemd[1]: leihs-migration.service: Unit entered failed state.
Jan 31 15:22:13 leihs systemd[1]: leihs-migration.service: Failed with result 'exit-code'.
```

**Comment by eins78** [comment]
I am assuming that this is about a fresh installation, using the Guide in this repository. 

From reading the logs, I can't think of a way how this could happen. 
Issuing `rake db:create` does not normally throw an error when the database already exists – the expected behaviour is to log `Database 'leihs' already exists` and then move onto the next task (`db:migrate`). 

The only thing that somehow stands out is the German error message. Having the server configured in a German locale should not break anything, but we only test and run on `en_US`, so we have no experience with that.

So, 2 things you can try that might make it work:
- upgrade to latest (unreleased) leihs version before installing. 
- try it with a freshly installed OS set to US-English (If a fresh install is too much work or otherwise no possible, I recommend [digitalocean](https://www.digitalocean.com) – a fresh server takes 1 Minute to set up and trying out the deploy and deleting it right after should cost just a few Euro-Cents)
  ***Please do tell us if that really makes a difference – we would at least note it in the documentation.***

**Comment by old-hell** [comment]
That's it. The System for Leihs needs to be US-English. The Ansible System can be German.
Thanks a lot :-)
