### ISSUE TITLE
Docker-Deploy stuck at TASK [install system python]

### ISSUE THREAD

**Issue by Befrog57** [leihs/leihs-instance#8]
When I start the deploy from Docker script it always exits with Permission denied (publickey,password).

Here the full code where it exits:
```
PLAY [all] *****************************************

TASK [install system python] ***********************************
fatal: [IP]: UNREACHABLE! => {
    "changed": false, 
    "unreachable": true
}

MSG:

Failed to connect to the host via ssh: Warning: Permanently added 'IP' (ECDSA) to the list of known hosts.
root@IP: Permission denied (publickey,password).



PLAY RECAP *************************
IP            : ok=0    changed=0    unreachable=1    failed=0   
```
I've already checked if my SSH-Keys are correctly set up and that seems to be the case.

**Comment by frankvanthof** [comment]
I have the exact same problem! Also checked if my SSH-Keys are correctly setup and everything works fine. Except the last part of the docker script. Already found a solution. I've been working on it all night..

**Comment by eins78** [comment]
> I've already checked if my SSH-Keys are correctly set up and that seems to be the case.

The script assumes you have a working ssh-agent set up and will pass that through to the Docker container.
You can try passing through your `.ssh` directory or just the keys. This is not built into the script because its not the proper thing to do in all cases, but if more people stumble upon this I can add it to the docs.

add the first line of this snippet to the `scripts/-from-docker` script (the other lines are just for context):

```sh
    -v "$HOME/.ssh:/root/.ssh" \
    -v "/run/host-services/ssh-auth.sock:/ssh-agent" \
    -e SSH_AUTH_SOCK="/ssh-agent" \
```

Alternatively, only pass through your key. That of course depends on how they're named on your system, so you need to give the full path – with the advantage that one could separate key just for that.

```sh
    -v "$HOME/.ssh/id_ed25519:/root/.ssh/id_ed25519" \
    -v "$HOME/.ssh/id_ed25519.pub:/root/.ssh/id_ed25519.pub" \
```

**Comment by frankvanthof** [comment]
Thanks for you reply. It really helped me out!
