### ISSUE TITLE
Leihs deploy-from-docker stuck at [leihs-mail-install : create jar]

### ISSUE THREAD

**Issue by Befrog57** [leihs/leihs-instance#9]
Hi there,
When I run the deploy-from-docker file everything seems to be fine until the Script is trying to execute the `[leihs-mail-install : create jar]` task. It just gets stuck. At first, I thought it might just take a while to install but after about 4-5h I was confident something was wrong. Here is a snippet of the deploy script with 5 times verbose turned on:
```
TASK [leihs-mail-install : create jar] ****************************************
task path: /leihs-instance/leihs/deploy/roles/leihs-mail-install/tasks/jar.yml:1
File lookup using /leihs-instance/leihs/deploy/helpers/build-artefact-with-s3-cache.bash as file
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/commands/command.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
```
There does not seem to be an error there, could you please take a look at that?

**Comment by eins78** [comment]
I've got good and bad news ;)
This kind of issue issue (it just hangs with nor error message) is basically impossible to debug from our side because it is caused by your specific environment. Personally I have seen many "hangs" caused by network issues. In very rare case the ansible process itself hangs, but bug reports about that have been (somewhat understandably) closed for the same reason.

But, the fact that you've reached this build steps alerted me to the fact that the prebuilt artefacts for the latest release had not been pushed to our public storage. Please try again now, it should not hang anymore at that step because it should be skipped altogether.

**Comment by Befrog57** [comment]
Hi it's me again,
I tried it right after you wrote your reply, back then it seemed to work fine, but I had to wait for another department to issue a SSL-Certificate. It arrived today and now it appears to be stuck again... Could you take a look at that (especially because it worked 3 Weeks ago)?

Kind Regards

**Comment by eins78** [comment]
> I tried it right after you wrote your reply, back then it seemed to work fine, but I had to wait for another department to issue a SSL-Certificate. It arrived today and now it appears to be stuck again... Could you take a look at that (especially because it worked 3 Weeks ago)?

Once again, you've acted as my monitoring system (it's on my todo list…).
Sorry, and please try again now.
